next xkcd check scheduled for: 38505419
bad user file: 533424598151069697.zeal
bad user file: 555965845629829120.zeal
Connected as EyanSays (Skarm). Yippee!
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Master9000 was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: Internal Server Error
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at IncomingMessage.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
KugallyBlitz was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Neon Strike Kitty was mentioned, but in a channel they can't view
next xkcd check scheduled for: 38505419
Master9000 was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Connected as EyanSays (Skarm). Yippee!
Dragonite was mentioned, but in a channel they can't view
next xkcd check scheduled for: 38505419
SuperGummying was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
KugallyBlitz was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: Forbidden (Cannot send messages to this user)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
SuperGummying was mentioned, but in a channel they can't view
139579058152275968 can't view the channel they were mentioned in for whatever reason
Connected as EyanSays (Skarm). Yippee!
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:7016) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.16.58.5:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:7016) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:7016) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.16.58.5:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
Connected as EyanSays (Skarm). Yippee!
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
Connected as EyanSays (Skarm). Yippee!
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
Connected as EyanSays (Skarm). Yippee!
(node:7016) UnhandledPromiseRejectionWarning: Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
    at Object.onceWrapper (events.js:277:13)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
SuperGummying was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
Demon_Lord was mentioned, but in a channel they can't view
Connected as EyanSays (Skarm). Yippee!
Dragonite was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
Connected as EyanSays (Skarm). Yippee!
(node:7016) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
(node:7016) UnhandledPromiseRejectionWarning: Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1088:19)
    at Object.onceWrapper (events.js:277:13)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:7016) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:7016) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at TLSSocket.socketOnEnd (_http_client.js:426:23)
    at TLSSocket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
Connected as EyanSays (Skarm). Yippee!
Connected as EyanSays (Skarm). Yippee!
Master9000 was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
next xkcd check scheduled for: 38505419
Connected as EyanSays (Skarm). Yippee!
KugallyBlitz was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: Internal Server Error
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at IncomingMessage.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
Neon Strike Kitty was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
139579058152275968 can't view the channel they were mentioned in for whatever reason
next xkcd check scheduled for: 38505419
next xkcd check scheduled for: 38505419
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
Connected as EyanSays (Skarm). Yippee!
Connected as EyanSays (Skarm). Yippee!
SuperGummying was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: Internal Server Error
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at IncomingMessage.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
Dragonite was mentioned, but in a channel they can't view
KugallyBlitz was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
next xkcd check scheduled for: 38505419
SuperGummying was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: Internal Server Error
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at IncomingMessage.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
(node:7016) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.16.59.5:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
(node:7016) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.16.59.5:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
Connected as EyanSays (Skarm). Yippee!
next xkcd check scheduled for: 38505419
Connected as EyanSays (Skarm). Yippee!
Rainy was mentioned, but in a channel they can't view
Master9000 was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
next xkcd check scheduled for: 38505419
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)
Skitty yeah.
SuperGummying was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.16.9.231:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45)
next xkcd check scheduled for: 38505419
next xkcd check scheduled for: 38505419
Connected as EyanSays (Skarm). Yippee!
KugallyBlitz was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: Internal Server Error
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at IncomingMessage.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
Master9000 was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
(node:7016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 47)
Dragonite was mentioned, but in a channel they can't view
next xkcd check scheduled for: 38505419
(node:7016) UnhandledPromiseRejectionWarning: Error: Forbidden (Missing Permissions)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 48)
SuperGummying was mentioned, but in a channel they can't view
KugallyBlitz was mentioned, but in a channel they can't view
Demon_Lord was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
next xkcd check scheduled for: 38505419
FLUBS was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
C:\bots\SkarmBot\bot.js:2107
			sms( e.message.channel, "_stabs dragonite_");
			     ^

ReferenceError: e is not defined
    at REACT (C:\bots\SkarmBot\bot.js:2107:9)
    at DiscordieDispatcher.client.Dispatcher.on.e (C:\bots\SkarmBot\bot.js:724:9)
    at DiscordieDispatcher.emit (events.js:189:13)
    at DiscordieDispatcher.emit (C:\bots\SkarmBot\node_modules\discordie\lib\core\DiscordieDispatcher.js:37:16)
    at Discordie.handler (C:\bots\SkarmBot\node_modules\discordie\lib\networking\messages\gateway\message_create.js:12:19)
    at Discordie.processMessage (C:\bots\SkarmBot\node_modules\discordie\lib\core\MessageHandlerCache.js:11:55)
    at MessageHandlerCache.processGatewayMessage (C:\bots\SkarmBot\node_modules\discordie\lib\core\MessageHandlerCache.js:53:27)
    at DiscordieDispatcher.Dispatcher.on.e (C:\bots\SkarmBot\node_modules\discordie\lib\index.js:82:19)
    at DiscordieDispatcher.emit (events.js:194:15)
    at DiscordieDispatcher.emit (C:\bots\SkarmBot\node_modules\discordie\lib\core\DiscordieDispatcher.js:37:16)
